
stages:
  - build
  - docker
  - deploy
# ----------------------------------------------------------------------------------------------------------------
maven-build:
  image: maven:latest
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
# -----------------------------------------------------------------
build-image:
  image: gitlab/dind
  services:
    - docker:dind
  stage: docker
  script:
    - docker build -t 123497/basic-springboot-cicd:latest .
    - docker login -u lephihung0997@gmail.com -p Hungphile@9397
    - docker push 123497/basic-springboot-cicd:latest
# -----------------------------------------------------------------
deploy-project:
  image: gitlab/dind
  services:
    - docker:dind
  stage: deploy
  script:
    - docker run -d -p 8081:8081 --name basic-springboot-cicd 123497/basic-springboot-cicd:latest
# -----------------------------------------------------------------